In [ ]:
# Import the `pandas` library as `pd`
import pandas as pd

# Load in the data with `read_csv()`
digits = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tra",
                     header=None)

In [ ]:
#take a look at the data
digits.describe()

0            1            2   ...           62           63           64
count  3823.0  3823.000000  3823.000000  ...  3823.000000  3823.000000  3823.000000
mean      0.0     0.301334     5.481821  ...     2.105676     0.202197     4.497253
std       0.0     0.866986     4.631601  ...     4.028266     1.150694     2.869831
min       0.0     0.000000     0.000000  ...     0.000000     0.000000     0.000000
25%       0.0     0.000000     1.000000  ...     0.000000     0.000000     2.000000
50%       0.0     0.000000     5.000000  ...     0.000000     0.000000     4.000000
75%       0.0     0.000000     9.000000  ...     2.000000     0.000000     7.000000
max       0.0     8.000000    16.000000  ...    16.000000    16.000000     9.000000

[8 rows x 65 columns]

In [ ]:
#check for nulls
null_vals = digits.isnull().sum()*100/len(digits)
null_vals_df = pd.DataFrame({'columns': digits.columns, 'null_perc':null_vals})

In [ ]:
null_vals_df.query('null_perc == 0 and columns == 0')

columns  null_perc
0        0        0.0

In [ ]:
#create few random null values
import numpy as np
import random

digits['nulls'] = np.random.normal(size=len(digits))
lst = random.sample(range(0, len(digits)), 5)
digits.at[lst, 'nulls'] = np.nan

In [ ]:
digits.iloc[lst]

0  1  2   3   4   5  6  7  8  ...  57  58  59  60  61  62  63  64  nulls
1452  0  0  2  13   9   1  0  0  0  ...   0   0  11  16   8   0   0   8    NaN
1016  0  0  2  14  15   8  0  0  0  ...   0   4  14  14  13   1   0   9    NaN
2641  0  0  2  13  16  16  9  0  0  ...   0   0  13   9   0   0   0   9    NaN
776   0  0  5  16  16  10  0  0  0  ...   0   5  16  16   8   0   0   8    NaN
3746  0  0  1  10   2   0  0  0  0  ...   0   2  15  16  16  13   1   6    NaN

[5 rows x 66 columns]

In [ ]:
#replace nulls with mean value of that column
mean_val = digits.nulls.notnull().mean()
digits.at[digits.nulls.isnull(), 'nulls'] = mean_val

In [ ]:
#do few aggregations
res1 = digits[digits[1] > 1].groupby(1, as_index = False).agg(
    {
        9 : ['sum', 'std'],
        10: 'mean'
    }
)

In [ ]:
res1

1    9                    10
      sum       std       mean
0  2  959  4.100889  13.363636
1  3  571  3.877046  13.200000
2  4  204  3.860493  13.181818
3  5   98  3.961352  12.285714
4  6   67  5.396758  13.375000
5  7   39  4.888763  10.333333
6  8    7  2.121320  11.000000

In [ ]:
res1.sort_values(by=(9, 'std'), ascending=False).head(3)

1    9                    10
      sum       std       mean
4  6   67  5.396758  13.375000
5  7   39  4.888763  10.333333
0  2  959  4.100889  13.363636

In [ ]:
#few string exercises
my_lst = ['Do', 'Re', 'Mi', 'Fa', 'Sol']

for element in my_lst: 
 print(element.lower())

my_lst2 = [x.lower() for x in my_lst]
my_lst2

do
re
mi
fa
sol


['do', 're', 'mi', 'fa', 'sol']

In [ ]:
'.'.join(my_lst2)

'do.re.mi.fa.sol'

In [ ]:
#fun with pandas
import pandas as pd
dct = {'a':1, 'b': 2}
lst = [[1,2,3], [2,3,4], [4,5,6]]
cols = ['a', 'b', 'c']
df = pd.DataFrame(data= lst, columns=cols)

In [ ]:
df2 = pd.DataFrame(data=lst, columns=cols)

In [ ]:
df.merge(df2, how='inner', left_on='a', right_on='b')

a_x  b_x  c_x  a_y  b_y  c_y
0    2    3    4    1    2    3

In [ ]:
df.join(df2, how='left', lsuffix='_l')

a_l  b_l  c_l  a  b  c
0    1    2    3  1  2  3
1    2    3    4  2  3  4
2    4    5    6  4  5  6

In [ ]:
df2

a  b  c
0  1  2  3
1  2  3  4
2  4  5  6

In [ ]:
#list sort
my_lst2.sort(key=lambda tup: tup[0], reverse=True)

In [ ]:
my_lst2

['sol', 're', 'mi', 'fa', 'do']

In [ ]:
sorted(my_lst2)

['do', 'fa', 'mi', 're', 'sol']

In [ ]:
my_lst2.sort(reverse=True)

In [ ]:
#convert dictionary to pandas
pd.DataFrame(dct.items())

0  1
0  a  1
1  b  2

In [ ]:
#numpy array
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
opa = np.zeros((2,3))

In [ ]:
opa1 = np.random.rand(7, 10, 10)

In [ ]:
opa1

array([[[4.23147808e-01, 4.93321867e-01, 8.68335849e-01, 1.41992363e-01,
         6.41213460e-01, 8.42591167e-01, 5.23065647e-01, 7.94762044e-01,
         4.52941850e-01, 8.15185911e-02],
        [6.19654955e-01, 1.43844556e-01, 6.29679161e-01, 7.58273851e-01,
         1.23844352e-01, 8.85838788e-01, 8.63061199e-01, 1.76073317e-01,
         9.04236486e-01, 7.72069886e-01],
        [9.31329327e-01, 5.65394533e-01, 4.59681783e-01, 6.97700745e-01,
         8.18745955e-01, 2.34785744e-01, 2.53035005e-01, 6.92083468e-01,
         6.79006428e-01, 8.86122573e-01],
        [5.20874161e-01, 9.87903430e-01, 3.50955604e-01, 7.45849826e-01,
         9.59795117e-01, 3.06870224e-01, 4.59863441e-01, 3.71924730e-01,
         3.00854551e-01, 6.47471891e-01],
        [9.35136457e-01, 3.81480830e-02, 9.75472278e-01, 6.95085208e-01,
         8.39795648e-01, 6.43037025e-01, 3.38477904e-01, 7.50137843e-01,
         6.34434273e-01, 2.27234722e-01],
        [9.98119596e-01, 8.12865604e-01, 9.53723523e-01, 3.0

In [ ]:
#accessing elements of numpy array
opa1[0:3, 1]

array([[0.61965495, 0.14384456, 0.62967916, 0.75827385, 0.12384435,
        0.88583879, 0.8630612 , 0.17607332, 0.90423649, 0.77206989],
       [0.69968128, 0.532378  , 0.4423837 , 0.59414935, 0.93700849,
        0.13479099, 0.80795447, 0.45634172, 0.36242091, 0.81882006],
       [0.98387716, 0.73310931, 0.22372703, 0.07512076, 0.05747535,
        0.70037045, 0.55879983, 0.88784567, 0.72908459, 0.89059924]])

In [ ]:
#given a list of whole numbers, find 2 numbers whose sum is equal to the target number
#e.g. [2, 4, 3, 1] if target = 3, print 2 and 1
lst = [2, 4, 3, 1]
target = 3
solutions = []
for i in range(len(lst)):
  for j in range(len(lst)):
    if lst[i] + lst[j] == target:
      solutions.append((lst[i], lst[j]))

print(solutions)

[(2, 1), (1, 2)]


In [ ]:
#let's optimze the solution above
#given a list of whole numbers, find 2 numbers whose sum is equal to the target number
#e.g. [2, 4, 3, 1] if target = 3, print 2 and 1
lst = [2, 2, 1]
target = 4
def find_pairs(lst, target):
  solutions = []
  i = 1
  for elem1 in lst:
    for elem2 in lst[i :]:
      if elem1 + elem2 == target:
        solutions.append((elem1, elem2))
    i += 1
    print("for list: ", lst, "and target:", target, ", solutions are:", solutions)
    return solutions
def run_tests(test_cases):
  for test in test_cases:
    find_pairs(test[0], test[1])

#define test cases:
test_cases = []
test_cases.append([[2, 2, 1], 4])
test_cases.append([[1, 2, 3, 2, 0, 7], 4])
test_cases.append([[1, 1, 1], 1])
run_tests(test_cases)


for list:  [2, 2, 1] and target: 4 , solutions are: [(2, 2)]
for list:  [1, 2, 3, 2, 0, 7] and target: 4 , solutions are: [(1, 3)]
for list:  [1, 1, 1] and target: 1 , solutions are: []


In [ ]:
#string comparisons
def words_matching (s1, s2):
  if s1.upper() == s2.upper():
    return True
  else:
    return False

def words_matching_1 (s1, s2):
  s1 = s1.upper()
  s2 = s2.upper()

  if len(s1) != len(s2):
    return False
  
  if hash(s1) != hash(s2):
    return False

  for i in range(len(s1)):
    if s1[i] != s2[i]:
      return False

  return True

words_matching_1('opp kj', 'OpP kj')

True

In [ ]:
#fun with array slicing
import numpy as np

foo = np.random.rand(10,3)
foo

array([[0.34000946, 0.954432  , 0.36996015],
       [0.61901813, 0.55272312, 0.99285525],
       [0.98833695, 0.66807604, 0.44993664],
       [0.29485308, 0.78334307, 0.75726718],
       [0.53282087, 0.56652793, 0.67524149],
       [0.93309698, 0.875017  , 0.66419101],
       [0.5636224 , 0.28840294, 0.8648289 ],
       [0.20452722, 0.26023092, 0.90723422],
       [0.46180719, 0.29989716, 0.35081765],
       [0.5520701 , 0.52384819, 0.45926894]])

In [ ]:
foo[1:3, 1:2]

array([[0.55272312],
       [0.66807604]])

In [ ]:
lst = [[2,3], [4,5], [6,7]]
foo = np.array(lst)
foo[0:, 0]

array([2, 4, 6])

In [ ]:
def do_reverse(lst):
  reversed = []
  for char in lst:
    reversed.insert(0, char)
  return ''.join(reversed)

lst = 'we want this in reverse'

print(do_reverse(lst))

esrever ni siht tnaw ew


In [ ]:
#list comprehension
lst = [1,4,5,2,0]
''.join([str(x) for x in lst])


'14520'

In [ ]:
#given two lists, find a missing element from the 1st list (1st list will always have a missing element)
lst1 = [3,2,7,9]
lst2 = [3,2,7,5,9]

def find_longer(lst1, lst2):
  if len(lst1) > len(lst2):
    return lst1, lst2
  else:
    return lst2, lst1

def find_missing(lst1, lst2):
  lst1, lst2 = find_longer(lst1, lst2)
  for elem in lst1:
    if elem not in lst2:
      print ('missing element:', elem)

def find_missing_v2(lst1, lst2):
  lst1, lst2 = find_longer(lst1, lst2)
  lst1.sort()
  lst2.sort()
  for elem1, elem2 in zip(lst1, lst2):
    if elem1 != elem2:
      print ('missing element:', elem1)
      return

find_missing_v2(lst1, lst2)

missing element: 5
